// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yecvvxirzmjqnjyrbuou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllY3Z2eGlyem1qcW5qeXJidW91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODc3NzEsImV4cCI6MjA1OTk2Mzc3MX0.qARDwmnGI07x_hVTFDDRum4-AhtzmI-Z3x27NOAO094";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);